In [1]:
import os
import pandas as pd
import numpy as np
import random
import warnings
random.seed(1) 
warnings.filterwarnings('ignore')
print('done importing')

done importing

### **Import and extract/read BRFSS2021 (CDC 2021 Health Indicators Survey) SAS (.XPT) file**

In [2]:
# Read SAS file
df= pd.read_sas("../Resources/LLCP2021.XPT")
df

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_FRTRES1,_VEGRES1,_FRUTSU1,_VEGESU1,_FRTLT1A,_VEGLT1A,_FRT16A,_VEG23A,_FRUITE1,_VEGETE1
0,1.0,1.0,b'01192021',b'01',b'19',b'2021',1100.0,b'2021000001',2.021000e+09,1.0,...,1.0,1.0,100.0,214.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
1,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000002',2.021000e+09,1.0,...,1.0,1.0,100.0,128.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
2,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000003',2.021000e+09,1.0,...,1.0,1.0,100.0,71.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79
3,1.0,1.0,b'01172021',b'01',b'17',b'2021',1100.0,b'2021000004',2.021000e+09,1.0,...,1.0,1.0,114.0,165.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
4,1.0,1.0,b'01152021',b'01',b'15',b'2021',1100.0,b'2021000005',2.021000e+09,1.0,...,1.0,1.0,100.0,258.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,78.0,12.0,b'01062022',b'01',b'06',b'2022',1100.0,b'2021001381',2.021001e+09,NaN,...,1.0,1.0,157.0,393.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438689,78.0,12.0,b'01122022',b'01',b'12',b'2022',1100.0,b'2021001382',2.021001e+09,NaN,...,1.0,1.0,200.0,157.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438690,78.0,12.0,b'12212021',b'12',b'21',b'2021',1100.0,b'2021001383',2.021001e+09,NaN,...,1.0,1.0,200.0,143.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438691,78.0,12.0,b'01112022',b'01',b'11',b'2022',1100.0,b'2021001384',2.021001e+09,NaN,...,1.0,1.0,100.0,156.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438692,78.0,12.0,b'12222021',b'12',b'22',b'2021',1100.0,b'2021001385',2.021001e+09,NaN,...,1.0,1.0,34.0,66.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79

In [3]:
# Eliminate fragmentation by creating a copy of DataFrame
df_bfrss2021 = df.copy()
df_bfrss2021

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_FRTRES1,_VEGRES1,_FRUTSU1,_VEGESU1,_FRTLT1A,_VEGLT1A,_FRT16A,_VEG23A,_FRUITE1,_VEGETE1
0,1.0,1.0,b'01192021',b'01',b'19',b'2021',1100.0,b'2021000001',2.021000e+09,1.0,...,1.0,1.0,100.0,214.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
1,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000002',2.021000e+09,1.0,...,1.0,1.0,100.0,128.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
2,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000003',2.021000e+09,1.0,...,1.0,1.0,100.0,71.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79
3,1.0,1.0,b'01172021',b'01',b'17',b'2021',1100.0,b'2021000004',2.021000e+09,1.0,...,1.0,1.0,114.0,165.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
4,1.0,1.0,b'01152021',b'01',b'15',b'2021',1100.0,b'2021000005',2.021000e+09,1.0,...,1.0,1.0,100.0,258.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,78.0,12.0,b'01062022',b'01',b'06',b'2022',1100.0,b'2021001381',2.021001e+09,NaN,...,1.0,1.0,157.0,393.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438689,78.0,12.0,b'01122022',b'01',b'12',b'2022',1100.0,b'2021001382',2.021001e+09,NaN,...,1.0,1.0,200.0,157.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438690,78.0,12.0,b'12212021',b'12',b'21',b'2021',1100.0,b'2021001383',2.021001e+09,NaN,...,1.0,1.0,200.0,143.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438691,78.0,12.0,b'01112022',b'01',b'11',b'2022',1100.0,b'2021001384',2.021001e+09,NaN,...,1.0,1.0,100.0,156.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438692,78.0,12.0,b'12222021',b'12',b'22',b'2021',1100.0,b'2021001385',2.021001e+09,NaN,...,1.0,1.0,34.0,66.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79

### **Define nature of the data**

In [4]:
# Get a list of all of the columns
df_bfrss2021.columns.values.tolist()

['_STATE',
 'FMONTH',
 'IDATE',
 'IMONTH',
 'IDAY',
 'IYEAR',
 'DISPCODE',
 'SEQNO',
 '_PSU',
 'CTELENM1',
 'PVTRESD1',
 'COLGHOUS',
 'STATERE1',
 'CELPHON1',
 'LADULT1',
 'COLGSEX',
 'NUMADULT',
 'LANDSEX',
 'NUMMEN',
 'NUMWOMEN',
 'RESPSLCT',
 'SAFETIME',
 'CTELNUM1',
 'CELLFON5',
 'CADULT1',
 'CELLSEX',
 'PVTRESD3',
 'CCLGHOUS',
 'CSTATE1',
 'LANDLINE',
 'HHADULT',
 'SEXVAR',
 'GENHLTH',
 'PHYSHLTH',
 'MENTHLTH',
 'POORHLTH',
 'PRIMINSR',
 'PERSDOC3',
 'MEDCOST1',
 'CHECKUP1',
 'EXERANY2',
 'BPHIGH6',
 'BPMEDS',
 'CHOLCHK3',
 'TOLDHI3',
 'CHOLMED3',
 'CVDINFR4',
 'CVDCRHD4',
 'CVDSTRK3',
 'ASTHMA3',
 'ASTHNOW',
 'CHCSCNCR',
 'CHCOCNCR',
 'CHCCOPD3',
 'ADDEPEV3',
 'CHCKDNY2',
 'DIABETE4',
 'DIABAGE3',
 'HAVARTH5',
 'ARTHEXER',
 'ARTHEDU',
 'LMTJOIN3',
 'ARTHDIS2',
 'JOINPAI2',
 'MARITAL',
 'EDUCA',
 'RENTHOM1',
 'NUMHHOL3',
 'NUMPHON3',
 'CPDEMO1B',
 'VETERAN3',
 'EMPLOY1',
 'CHILDREN',
 'INCOME3',
 'PREGNANT',
 'WEIGHT2',
 'HEIGHT3',
 'DEAF',
 'BLIND',
 'DECIDE',
 'DIFFWALK',
 'DIFFDRES',
 'DIFFALON',
 'SMOKE100',
 'SMOKDAY2',
 'USENOW3',
 'ECIGNOW1',
 'ALCDAY5',
 'AVEDRNK3',
 'DRNK3GE5',
 'MAXDRNKS',
 'FLUSHOT7',
 'FLSHTMY3',
 'IMFVPLA2',
 'PNEUVAC4',
 'HIVTST7',
 'HIVTSTD3',
 'FRUIT2',
 'FRUITJU2',
 'FVGREEN1',
 'FRENCHF1',
 'POTATOE1',
 'VEGETAB2',
 'PDIABTST',
 'PREDIAB1',
 'INSULIN1',
 'BLDSUGAR',
 'FEETCHK3',
 'DOCTDIAB',
 'CHKHEMO3',
 'FEETCHK',
 'EYEEXAM1',
 'DIABEYE',
 'DIABEDU',
 'TOLDCFS',
 'HAVECFS',
 'WORKCFS',
 'TOLDHEPC',
 'TRETHEPC',
 'PRIRHEPC',
 'HAVEHEPC',
 'HAVEHEPB',
 'MEDSHEPB',
 'HPVADVC4',
 'HPVADSHT',
 'TETANUS1',
 'SHINGLE2',
 'LCSFIRST',
 'LCSLAST',
 'LCSNUMCG',
 'LCSCTSCN',
 'HADMAM',
 'HOWLONG',
 'CERVSCRN',
 'CRVCLCNC',
 'CRVCLPAP',
 'CRVCLHPV',
 'HADHYST2',
 'PSATEST1',
 'PSATIME1',
 'PCPSARS2',
 'PCSTALK',
 'HADSIGM4',
 'COLNSIGM',
 'COLNTES1',
 'SIGMTES1',
 'LASTSIG4',
 'COLNCNCR',
 'VIRCOLO1',
 'VCLNTES1',
 'SMALSTOL',
 'STOLTEST',
 'STOOLDN1',
 'BLDSTFIT',
 'SDNATES1',
 'CNCRDIFF',
 'CNCRAGE',
 'CNCRTYP1',
 'CSRVTRT3',
 'CSRVDOC1',
 'CSRVSUM',
 'CSRVRTRN',
 'CSRVINST',
 'CSRVINSR',
 'CSRVDEIN',
 'CSRVCLIN',
 'CSRVPAIN',
 'CSRVCTL2',
 'HOMBPCHK',
 'HOMRGCHK',
 'WHEREBP',
 'SHAREBP',
 'WTCHSALT',
 'DRADVISE',
 'CIMEMLOS',
 'CDHOUSE',
 'CDASSIST',
 'CDHELP',
 'CDSOCIAL',
 'CDDISCUS',
 'CAREGIV1',
 'CRGVREL4',
 'CRGVLNG1',
 'CRGVHRS1',
 'CRGVPRB3',
 'CRGVALZD',
 'CRGVPER1',
 'CRGVHOU1',
 'CRGVEXPT',
 'ACEDEPRS',
 'ACEDRINK',
 'ACEDRUGS',
 'ACEPRISN',
 'ACEDIVRC',
 'ACEPUNCH',
 'ACEHURT1',
 'ACESWEAR',
 'ACETOUCH',
 'ACETTHEM',
 'ACEHVSEX',
 'ACEADSAF',
 'ACEADNED',
 'MARIJAN1',
 'USEMRJN3',
 'RSNMRJN2',
 'LASTSMK2',
 'STOPSMK2',
 'FIREARM5',
 'GUNLOAD',
 'LOADULK2',
 'RCSGENDR',
 'RCSRLTN2',
 'CASTHDX2',
 'CASTHNO2',
 'BIRTHSEX',
 'SOMALE',
 'SOFEMALE',
 'TRNSGNDR',
 'QSTVER',
 'QSTLANG',
 '_METSTAT',
 '_URBSTAT',
 'MSCODE',
 '_STSTR',
 '_STRWT',
 '_RAWRAKE',
 '_WT2RAKE',
 '_IMPRACE',
 '_CHISPNC',
 '_CRACE1',
 '_CPRACE1',
 'CAGEG',
 '_CLLCPWT',
 '_DUALUSE',
 '_DUALCOR',
 '_LLCPWT2',
 '_LLCPWT',
 '_RFHLTH',
 '_PHYS14D',
 '_MENT14D',
 '_HLTHPLN',
 '_HCVU652',
 '_TOTINDA',
 '_RFHYPE6',
 '_CHOLCH3',
 '_RFCHOL3',
 '_MICHD',
 '_LTASTH1',
 '_CASTHM1',
 '_ASTHMS1',
 '_DRDXAR3',
 '_LMTACT3',
 '_LMTWRK3',
 '_PRACE1',
 '_MRACE1',
 '_HISPANC',
 '_RACE',
 '_RACEG21',
 '_RACEGR3',
 '_RACEPRV',
 '_SEX',
 '_AGEG5YR',
 '_AGE65YR',
 '_AGE80',
 '_AGE_G',
 'HTIN4',
 'HTM4',
 'WTKG3',
 '_BMI5',
 '_BMI5CAT',
 '_RFBMI5',
 '_CHLDCNT',
 '_EDUCAG',
 '_INCOMG1',
 '_SMOKER3',
 '_RFSMOK3',
 '_CURECI1',
 'DRNKANY5',
 'DROCDY3_',
 '_RFBING5',
 '_DRNKWK1',
 '_RFDRHV7',
 '_FLSHOT7',
 '_PNEUMO3',
 '_AIDTST4',
 'FTJUDA2_',
 'FRUTDA2_',
 'GRENDA1_',
 'FRNCHDA_',
 'POTADA1_',
 'VEGEDA2_',
 '_MISFRT1',
 '_MISVEG1',
 '_FRTRES1',
 '_VEGRES1',
 '_FRUTSU1',
 '_VEGESU1',
 '_FRTLT1A',
 '_VEGLT1A',
 '_FRT16A',
 '_VEG23A',
 '_FRUITE1',
 '_VEGETE1']

In [5]:
# Determine the number of null values in each column
nan_sum = df_bfrss2021.isnull().sum()
pd.options.display.max_rows = 4000

print(nan_sum)

_STATE           0
FMONTH           0
IDATE            0
IMONTH           0
IDAY             0
IYEAR            0
DISPCODE         0
SEQNO            0
_PSU             0
CTELENM1    320907
PVTRESD1    320907
COLGHOUS    438663
STATERE1    320907
CELPHON1    320907
LADULT1     320907
COLGSEX     438663
NUMADULT    320926
LANDSEX     388847
NUMMEN      373255
NUMWOMEN    373255
RESPSLCT    374029
SAFETIME    117786
CTELNUM1    117787
CELLFON5    117786
CADULT1     117786
CELLSEX     117788
PVTRESD3    117786
CCLGHOUS    437438
CSTATE1     117786
LANDLINE    117786
HHADULT     117788
SEXVAR           0
GENHLTH          4
PHYSHLTH         3
MENTHLTH         2
POORHLTH    205279
PRIMINSR         3
PERSDOC3         2
MEDCOST1         5
CHECKUP1         2
EXERANY2         2
BPHIGH6          2
BPMEDS      266560
CHOLCHK3         2
TOLDHI3      60836
CHOLMED3     61571
CVDINFR4         2
CVDCRHD4         2
CVDSTRK3         2
ASTHMA3          2
ASTHNOW     377191
CHCSCNCR         2
CHCOCNCR         3
CHCCOPD3         3
ADDEPEV3         3
CHCKDNY2         3
DIABETE4         3
DIABAGE3    381078
HAVARTH5         3
ARTHEXER    296152
ARTHEDU     296152
LMTJOIN3    296152
ARTHDIS2    296153
JOINPAI2    296154
MARITAL          5
EDUCA            5
RENTHOM1         8
NUMHHOL3    320910
NUMPHON3    406880
CPDEMO1B       292
VETERAN3      1636
EMPLOY1       3588
CHILDREN      6135
INCOME3       8847
PREGNANT    358021
WEIGHT2      11816
HEIGHT3      12959
DEAF         14602
BLIND        15744
DECIDE       16843
DIFFWALK     18009
DIFFDRES     18786
DIFFALON     19853
SMOKE100     21232
SMOKDAY2    271240
USENOW3      21989
ECIGNOW1     23025
ALCDAY5      24487
AVEDRNK3    228271
DRNK3GE5    228868
MAXDRNKS    229430
FLUSHOT7     27648
FLSHTMY3    227057
IMFVPLA2    230300
PNEUVAC4     29087
HIVTST7      30151
HIVTSTD3    309898
FRUIT2       34175
FRUITJU2     35762
FVGREEN1     36995
FRENCHF1     38111
POTATOE1     39306
VEGETAB2     40615
PDIABTST    324075
PREDIAB1    324076
INSULIN1    416455
BLDSUGAR    416454
FEETCHK3    416460
DOCTDIAB    416463
CHKHEMO3    416464
FEETCHK     416630
EYEEXAM1    416468
DIABEYE     416471
DIABEDU     416472
TOLDCFS     438693
HAVECFS     438693
WORKCFS     438693
TOLDHEPC    427889
TRETHEPC    438531
PRIRHEPC    438531
HAVEHEPC    438531
HAVEHEPB    427914
MEDSHEPB    438598
HPVADVC4    425379
HPVADSHT    436183
TETANUS1    423816
SHINGLE2    425141
LCSFIRST    426166
LCSLAST     426575
LCSNUMCG    426594
LCSCTSCN    408532
HADMAM      429170
HOWLONG     431237
CERVSCRN    429185
CRVCLCNC    433810
CRVCLPAP    433847
CRVCLHPV    433829
HADHYST2    429293
PSATEST1    436441
PSATIME1    437573
PCPSARS2    437574
PCSTALK     437576
HADSIGM4    430916
COLNSIGM    433086
COLNTES1    434102
SIGMTES1    438630
LASTSIG4    437746
COLNCNCR    430922
VIRCOLO1    437077
VCLNTES1    438490
SMALSTOL    437077
STOLTEST    437462
STOOLDN1    437078
BLDSTFIT    438303
SDNATES1    438303
CNCRDIFF    428730
CNCRAGE     428896
CNCRTYP1    428905
CSRVTRT3    431374
CSRVDOC1    434251
CSRVSUM     434258
CSRVRTRN    434263
CSRVINST    435314
CSRVINSR    434267
CSRVDEIN    434269
CSRVCLIN    434272
CSRVPAIN    429677
CSRVCTL2    437842
HOMBPCHK    312692
HOMRGCHK    312724
WHEREBP     399155
SHAREBP     399168
WTCHSALT    402584
DRADVISE    402613
CIMEMLOS    405542
CDHOUSE     434324
CDASSIST    434332
CDHELP      437414
CDSOCIAL    434342
CDDISCUS    434348
CAREGIV1    250465
CRGVREL4    399892
CRGVLNG1    399976
CRGVHRS1    400062
CRGVPRB3    400179
CRGVALZD    404019
CRGVPER1    400353
CRGVHOU1    400422
CRGVEXPT    289886
ACEDEPRS    379930
ACEDRINK    380046
ACEDRUGS    380076
ACEPRISN    380114
ACEDIVRC    380146
ACEPUNCH    380188
ACEHURT1    380232
ACESWEAR    380277
ACETOUCH    380330
ACETTHEM    380374
ACEHVSEX    380415
ACEADSAF    380487
ACEADNED    380537
MARIJAN1    301133
USEMRJN3    425147
RSNMRJN2    425161
LASTSMK2    386840
STOPSMK2    414631
FIREARM5    408125
GUNLOAD     426539
LOADULK2    434376
RCSGENDR    381636
RCSRLTN2    382013
CASTHDX2    383874
CASTHNO2    432927
BIRTHSEX    340191
SOMALE      324524
SOFEMALE    307374
TRNSGNDR    192949
QSTVER           0
QSTLANG          0
_METSTAT      7054
_URBSTAT      7054
MSCODE      322720
_STSTR           0
_STRWT           0
_RAWRAKE         0
_WT2RAKE         0
_IMPRACE         0
_CHISPNC    126819
_CRACE1     378994
_CPRACE1    378994
CAGEG       390113
_CLLCPWT    381599
_DUALUSE         0
_DUALCOR    264965
_LLCPWT2         0
_LLCPWT          0
_RFHLTH          0
_PHYS14D         0
_MENT14D         0
_HLTHPLN         0
_HCVU652         0
_TOTINDA         0
_RFHYPE6         0
_CHOLCH3         0
_RFCHOL3     61151
_MICHD        4635
_LTASTH1         0
_CASTHM1         0
_ASTHMS1         0
_DRDXAR3      2896
_LMTACT3      2896
_LMTWRK3      2896
_PRACE1          4
_MRACE1          4
_HISPANC         0
_RACE            0
_RACEG21         0
_RACEGR3         0
_RACEPRV         0
_SEX             0
_AGEG5YR         0
_AGE65YR         0
_AGE80           0
_AGE_G           0
HTIN4        27150
HTM4         24562
WTKG3        40588
_BMI5        46852
_BMI5CAT     46852
_RFBMI5          0
_CHLDCNT         0
_EDUCAG          0
_INCOMG1         0
_SMOKER3         0
_RFSMOK3         0
_CURECI1         0
DRNKANY5         0
DROCDY3_         0
_RFBING5         0
_DRNKWK1         0
_RFDRHV7         0
_FLSHOT7    276150
_PNEUMO3    276150
_AIDTST4     30151
FTJUDA2_     44349
FRUTDA2_     43951
GRENDA1_     44250
FRNCHDA_     44765
POTADA1_     48440
VEGEDA2_     48528
_MISFRT1         0
_MISVEG1         0
_FRTRES1         0
_VEGRES1         0
_FRUTSU1     51087
_VEGESU1     60127
_FRTLT1A         0
_VEGLT1A         0
_FRT16A          0
_VEG23A          0
_FRUITE1         0
_VEGETE1         0
dtype: int64

In [6]:
# Percentage of missing values
nan_mean = df_bfrss2021.isnull().mean()
pd.options.display.max_rows = 4000

print(nan_mean)

_STATE      0.000000
FMONTH      0.000000
IDATE       0.000000
IMONTH      0.000000
IDAY        0.000000
IYEAR       0.000000
DISPCODE    0.000000
SEQNO       0.000000
_PSU        0.000000
CTELENM1    0.731507
PVTRESD1    0.731507
COLGHOUS    0.999932
STATERE1    0.731507
CELPHON1    0.731507
LADULT1     0.731507
COLGSEX     0.999932
NUMADULT    0.731550
LANDSEX     0.886376
NUMMEN      0.850834
NUMWOMEN    0.850834
RESPSLCT    0.852599
SAFETIME    0.268493
CTELNUM1    0.268495
CELLFON5    0.268493
CADULT1     0.268493
CELLSEX     0.268498
PVTRESD3    0.268493
CCLGHOUS    0.997139
CSTATE1     0.268493
LANDLINE    0.268493
HHADULT     0.268498
SEXVAR      0.000000
GENHLTH     0.000009
PHYSHLTH    0.000007
MENTHLTH    0.000005
POORHLTH    0.467933
PRIMINSR    0.000007
PERSDOC3    0.000005
MEDCOST1    0.000011
CHECKUP1    0.000005
EXERANY2    0.000005
BPHIGH6     0.000005
BPMEDS      0.607623
CHOLCHK3    0.000005
TOLDHI3     0.138676
CHOLMED3    0.140351
CVDINFR4    0.000005
CVDCRHD4    0.000005
CVDSTRK3    0.000005
ASTHMA3     0.000005
ASTHNOW     0.859806
CHCSCNCR    0.000005
CHCOCNCR    0.000007
CHCCOPD3    0.000007
ADDEPEV3    0.000007
CHCKDNY2    0.000007
DIABETE4    0.000007
DIABAGE3    0.868667
HAVARTH5    0.000007
ARTHEXER    0.675078
ARTHEDU     0.675078
LMTJOIN3    0.675078
ARTHDIS2    0.675080
JOINPAI2    0.675083
MARITAL     0.000011
EDUCA       0.000011
RENTHOM1    0.000018
NUMHHOL3    0.731514
NUMPHON3    0.927482
CPDEMO1B    0.000666
VETERAN3    0.003729
EMPLOY1     0.008179
CHILDREN    0.013985
INCOME3     0.020167
PREGNANT    0.816108
WEIGHT2     0.026935
HEIGHT3     0.029540
DEAF        0.033285
BLIND       0.035888
DECIDE      0.038394
DIFFWALK    0.041051
DIFFDRES    0.042823
DIFFALON    0.045255
SMOKE100    0.048398
SMOKDAY2    0.618291
USENOW3     0.050124
ECIGNOW1    0.052485
ALCDAY5     0.055818
AVEDRNK3    0.520343
DRNK3GE5    0.521704
MAXDRNKS    0.522985
FLUSHOT7    0.063024
FLSHTMY3    0.517576
IMFVPLA2    0.524968
PNEUVAC4    0.066304
HIVTST7     0.068729
HIVTSTD3    0.706412
FRUIT2      0.077902
FRUITJU2    0.081519
FVGREEN1    0.084330
FRENCHF1    0.086874
POTATOE1    0.089598
VEGETAB2    0.092582
PDIABTST    0.738728
PREDIAB1    0.738731
INSULIN1    0.949309
BLDSUGAR    0.949306
FEETCHK3    0.949320
DOCTDIAB    0.949327
CHKHEMO3    0.949329
FEETCHK     0.949707
EYEEXAM1    0.949338
DIABEYE     0.949345
DIABEDU     0.949347
TOLDCFS     1.000000
HAVECFS     1.000000
WORKCFS     1.000000
TOLDHEPC    0.975372
TRETHEPC    0.999631
PRIRHEPC    0.999631
HAVEHEPC    0.999631
HAVEHEPB    0.975429
MEDSHEPB    0.999783
HPVADVC4    0.969651
HPVADSHT    0.994278
TETANUS1    0.966088
SHINGLE2    0.969108
LCSFIRST    0.971445
LCSLAST     0.972377
LCSNUMCG    0.972420
LCSCTSCN    0.931248
HADMAM      0.978292
HOWLONG     0.983004
CERVSCRN    0.978327
CRVCLCNC    0.988869
CRVCLPAP    0.988954
CRVCLHPV    0.988913
HADHYST2    0.978573
PSATEST1    0.994867
PSATIME1    0.997447
PCPSARS2    0.997449
PCSTALK     0.997454
HADSIGM4    0.982272
COLNSIGM    0.987219
COLNTES1    0.989535
SIGMTES1    0.999856
LASTSIG4    0.997841
COLNCNCR    0.982286
VIRCOLO1    0.996316
VCLNTES1    0.999537
SMALSTOL    0.996316
STOLTEST    0.997194
STOOLDN1    0.996319
BLDSTFIT    0.999111
SDNATES1    0.999111
CNCRDIFF    0.977289
CNCRAGE     0.977668
CNCRTYP1    0.977688
CSRVTRT3    0.983316
CSRVDOC1    0.989874
CSRVSUM     0.989890
CSRVRTRN    0.989902
CSRVINST    0.992298
CSRVINSR    0.989911
CSRVDEIN    0.989915
CSRVCLIN    0.989922
CSRVPAIN    0.979448
CSRVCTL2    0.998060
HOMBPCHK    0.712781
HOMRGCHK    0.712854
WHEREBP     0.909873
SHAREBP     0.909903
WTCHSALT    0.917690
DRADVISE    0.917756
CIMEMLOS    0.924432
CDHOUSE     0.990041
CDASSIST    0.990059
CDHELP      0.997085
CDSOCIAL    0.990082
CDDISCUS    0.990096
CAREGIV1    0.570935
CRGVREL4    0.911553
CRGVLNG1    0.911745
CRGVHRS1    0.911941
CRGVPRB3    0.912207
CRGVALZD    0.920961
CRGVPER1    0.912604
CRGVHOU1    0.912761
CRGVEXPT    0.660795
ACEDEPRS    0.866050
ACEDRINK    0.866314
ACEDRUGS    0.866383
ACEPRISN    0.866469
ACEDIVRC    0.866542
ACEPUNCH    0.866638
ACEHURT1    0.866738
ACESWEAR    0.866841
ACETOUCH    0.866962
ACETTHEM    0.867062
ACEHVSEX    0.867155
ACEADSAF    0.867320
ACEADNED    0.867433
MARIJAN1    0.686432
USEMRJN3    0.969122
RSNMRJN2    0.969154
LASTSMK2    0.881801
STOPSMK2    0.945151
FIREARM5    0.930320
GUNLOAD     0.972295
LOADULK2    0.990159
RCSGENDR    0.869939
RCSRLTN2    0.870798
CASTHDX2    0.875040
CASTHNO2    0.986856
BIRTHSEX    0.775465
SOMALE      0.739752
SOFEMALE    0.700659
TRNSGNDR    0.439827
QSTVER      0.000000
QSTLANG     0.000000
_METSTAT    0.016080
_URBSTAT    0.016080
MSCODE      0.735640
_STSTR      0.000000
_STRWT      0.000000
_RAWRAKE    0.000000
_WT2RAKE    0.000000
_IMPRACE    0.000000
_CHISPNC    0.289084
_CRACE1     0.863916
_CPRACE1    0.863916
CAGEG       0.889262
_CLLCPWT    0.869854
_DUALUSE    0.000000
_DUALCOR    0.603987
_LLCPWT2    0.000000
_LLCPWT     0.000000
_RFHLTH     0.000000
_PHYS14D    0.000000
_MENT14D    0.000000
_HLTHPLN    0.000000
_HCVU652    0.000000
_TOTINDA    0.000000
_RFHYPE6    0.000000
_CHOLCH3    0.000000
_RFCHOL3    0.139394
_MICHD      0.010565
_LTASTH1    0.000000
_CASTHM1    0.000000
_ASTHMS1    0.000000
_DRDXAR3    0.006601
_LMTACT3    0.006601
_LMTWRK3    0.006601
_PRACE1     0.000009
_MRACE1     0.000009
_HISPANC    0.000000
_RACE       0.000000
_RACEG21    0.000000
_RACEGR3    0.000000
_RACEPRV    0.000000
_SEX        0.000000
_AGEG5YR    0.000000
_AGE65YR    0.000000
_AGE80      0.000000
_AGE_G      0.000000
HTIN4       0.061888
HTM4        0.055989
WTKG3       0.092520
_BMI5       0.106799
_BMI5CAT    0.106799
_RFBMI5     0.000000
_CHLDCNT    0.000000
_EDUCAG     0.000000
_INCOMG1    0.000000
_SMOKER3    0.000000
_RFSMOK3    0.000000
_CURECI1    0.000000
DRNKANY5    0.000000
DROCDY3_    0.000000
_RFBING5    0.000000
_DRNKWK1    0.000000
_RFDRHV7    0.000000
_FLSHOT7    0.629483
_PNEUMO3    0.629483
_AIDTST4    0.068729
FTJUDA2_    0.101093
FRUTDA2_    0.100186
GRENDA1_    0.100868
FRNCHDA_    0.102042
POTADA1_    0.110419
VEGEDA2_    0.110619
_MISFRT1    0.000000
_MISVEG1    0.000000
_FRTRES1    0.000000
_VEGRES1    0.000000
_FRUTSU1    0.116453
_VEGESU1    0.137059
_FRTLT1A    0.000000
_VEGLT1A    0.000000
_FRT16A     0.000000
_VEG23A     0.000000
_FRUITE1    0.000000
_VEGETE1    0.000000
dtype: float64

The majority of rows and columns include missing data.  As the dataset reflects the results if a comprehensive survey, one would expect to find a large number of missing data, and that the nature of the missing data would be highly variable and random.  Deleting rows or columns would remove most indicators.  The best approach is to fill in missing data.  Missing values are of the MCAR type, meaning there is absolutely no relationship between the data missing and any other observed or missing value in the dataset. In other words, those missing data points are a random subset of the dataset.  The most effective approach is to use a random sample imputer (using median) to fill in the missing data.

In [7]:
# Fill in NaN values with Random Sampler Imputation by Median
df_bfrss2021.fillna(df_bfrss2021.median())

,_STATE,FMONTH,IDATE,IMONTH,IDAY,IYEAR,DISPCODE,SEQNO,_PSU,CTELENM1,...,_FRTRES1,_VEGRES1,_FRUTSU1,_VEGESU1,_FRTLT1A,_VEGLT1A,_FRT16A,_VEG23A,_FRUITE1,_VEGETE1
0,1.0,1.0,b'01192021',b'01',b'19',b'2021',1100.0,b'2021000001',2.021000e+09,1.0,...,1.0,1.0,100.0,214.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
1,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000002',2.021000e+09,1.0,...,1.0,1.0,100.0,128.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
2,1.0,1.0,b'01212021',b'01',b'21',b'2021',1100.0,b'2021000003',2.021000e+09,1.0,...,1.0,1.0,100.0,71.0,1.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79
3,1.0,1.0,b'01172021',b'01',b'17',b'2021',1100.0,b'2021000004',2.021000e+09,1.0,...,1.0,1.0,114.0,165.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
4,1.0,1.0,b'01152021',b'01',b'15',b'2021',1100.0,b'2021000005',2.021000e+09,1.0,...,1.0,1.0,100.0,258.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,78.0,12.0,b'01062022',b'01',b'06',b'2022',1100.0,b'2021001381',2.021001e+09,1.0,...,1.0,1.0,157.0,393.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438689,78.0,12.0,b'01122022',b'01',b'12',b'2022',1100.0,b'2021001382',2.021001e+09,1.0,...,1.0,1.0,200.0,157.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438690,78.0,12.0,b'12212021',b'12',b'21',b'2021',1100.0,b'2021001383',2.021001e+09,1.0,...,1.0,1.0,200.0,143.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438691,78.0,12.0,b'01112022',b'01',b'11',b'2022',1100.0,b'2021001384',2.021001e+09,1.0,...,1.0,1.0,100.0,156.0,1.0,1.0,1.0,1.0,5.397605e-79,5.397605e-79
438692,78.0,12.0,b'12222021',b'12',b'22',b'2021',1100.0,b'2021001385',2.021001e+09,1.0,...,1.0,1.0,34.0,66.0,2.0,2.0,1.0,1.0,5.397605e-79,5.397605e-79

### Using established research, we will narrow the available 303 indicators to reflect features that are known indicators for diabetes.

In [8]:
# Pre-diabetes diagnoses are incorporated in the DIABETE4 feature.  As a valuable indicator for diabetes, we will isolate this feature in a new column
# Add Prediabetic column
df_bfrss2021['PREDIAB'] = df_bfrss2021['DIABETE4']

In [9]:
# select chosen columns
brfss_df_selected = df_bfrss2021[['DISPCODE',
                                'DIABETE4',
                                'PREDIAB', 
                                'MEDCOST1',
                                '_PHYS14D',
                                '_MENT14D',
                                'EXERANY2',
                                'CVDINFR4',
                                'CVDCRHD4',
                                'CVDSTRK3',
                                'CHCCOPD3',
                                'CHCKDNY2',
                                'DIFFWALK',
                                '_IMPRACE',
                                '_RFHLTH',
                                '_HLTHPLN',
                                '_TOTINDA',
                                '_RFHYPE6',
                                '_SEX',
                                '_AGE_G',
                                '_RFBMI5',
                                '_EDUCAG',
                                '_INCOMG1',
                                '_SMOKER3',
                                '_RFBING5',
                                '_RFDRHV7',
                                '_FRTLT1A',
                                '_VEGLT1A',]]
brfss_df_selected

,DISPCODE,DIABETE4,PREDIAB,MEDCOST1,_PHYS14D,_MENT14D,EXERANY2,CVDINFR4,CVDCRHD4,CVDSTRK3,...,_SEX,_AGE_G,_RFBMI5,_EDUCAG,_INCOMG1,_SMOKER3,_RFBING5,_RFDRHV7,_FRTLT1A,_VEGLT1A
0,1100.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,...,2.0,6.0,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0
1,1100.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,...,2.0,6.0,9.0,4.0,9.0,4.0,1.0,1.0,1.0,1.0
2,1100.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,...,2.0,6.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,2.0
3,1100.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,...,2.0,5.0,2.0,2.0,5.0,4.0,2.0,1.0,1.0,1.0
4,1100.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0,7.0,1.0,...,1.0,6.0,2.0,1.0,2.0,4.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,1100.0,2.0,2.0,1.0,1.0,3.0,1.0,2.0,2.0,2.0,...,2.0,2.0,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0
438689,1100.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,...,1.0,6.0,9.0,2.0,1.0,4.0,1.0,1.0,1.0,1.0
438690,1100.0,3.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,...,1.0,4.0,2.0,4.0,6.0,4.0,1.0,1.0,1.0,1.0
438691,1100.0,3.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,...,1.0,6.0,1.0,2.0,4.0,4.0,1.0,1.0,1.0,1.0
438692,1100.0,3.0,3.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,...,2.0,4.0,2.0,4.0,4.0,4.0,1.0,1.0,2.0,2.0

In [10]:
# The dataset includes an indicator for only partially collected survey results.
# As these are likely to skew our data, we will remove them in favour of creating models on a higher degree of complete data.
# Drop ny rows where survey has only been partially completed (dispcode = 1200)
brfss_df_selected.drop(brfss_df_selected[brfss_df_selected['DISPCODE'] >= 1200].index, inplace = True)
brfss_df_selected

,DISPCODE,DIABETE4,PREDIAB,MEDCOST1,_PHYS14D,_MENT14D,EXERANY2,CVDINFR4,CVDCRHD4,CVDSTRK3,...,_SEX,_AGE_G,_RFBMI5,_EDUCAG,_INCOMG1,_SMOKER3,_RFBING5,_RFDRHV7,_FRTLT1A,_VEGLT1A
0,1100.0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,...,2.0,6.0,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0
1,1100.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,...,2.0,6.0,9.0,4.0,9.0,4.0,1.0,1.0,1.0,1.0
2,1100.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,...,2.0,6.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,2.0
3,1100.0,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,...,2.0,5.0,2.0,2.0,5.0,4.0,2.0,1.0,1.0,1.0
4,1100.0,1.0,1.0,2.0,3.0,1.0,1.0,1.0,7.0,1.0,...,1.0,6.0,2.0,1.0,2.0,4.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,1100.0,2.0,2.0,1.0,1.0,3.0,1.0,2.0,2.0,2.0,...,2.0,2.0,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0
438689,1100.0,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,...,1.0,6.0,9.0,2.0,1.0,4.0,1.0,1.0,1.0,1.0
438690,1100.0,3.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,...,1.0,4.0,2.0,4.0,6.0,4.0,1.0,1.0,1.0,1.0
438691,1100.0,3.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,...,1.0,6.0,1.0,2.0,4.0,4.0,1.0,1.0,1.0,1.0
438692,1100.0,3.0,3.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,...,2.0,4.0,2.0,4.0,4.0,4.0,1.0,1.0,2.0,2.0

In [11]:
# Drop DISPCODE column as it is no longer needed
brfss_df_selected = brfss_df_selected.drop('DISPCODE', axis=1)

In [12]:
# Create a copy of DataFrame
brfss_df_clean = brfss_df_selected.copy()
brfss_df_clean

,DIABETE4,PREDIAB,MEDCOST1,_PHYS14D,_MENT14D,EXERANY2,CVDINFR4,CVDCRHD4,CVDSTRK3,CHCCOPD3,...,_SEX,_AGE_G,_RFBMI5,_EDUCAG,_INCOMG1,_SMOKER3,_RFBING5,_RFDRHV7,_FRTLT1A,_VEGLT1A
0,3.0,3.0,2.0,3.0,2.0,2.0,2.0,2.0,2.0,1.0,...,2.0,6.0,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0
1,1.0,1.0,2.0,1.0,1.0,1.0,2.0,1.0,2.0,2.0,...,2.0,6.0,9.0,4.0,9.0,4.0,1.0,1.0,1.0,1.0
2,1.0,1.0,2.0,1.0,1.0,2.0,2.0,1.0,2.0,2.0,...,2.0,6.0,2.0,2.0,2.0,4.0,1.0,1.0,1.0,2.0
3,1.0,1.0,2.0,1.0,2.0,1.0,2.0,2.0,2.0,2.0,...,2.0,5.0,2.0,2.0,5.0,4.0,2.0,1.0,1.0,1.0
4,1.0,1.0,2.0,3.0,1.0,1.0,1.0,7.0,1.0,2.0,...,1.0,6.0,2.0,1.0,2.0,4.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438688,2.0,2.0,1.0,1.0,3.0,1.0,2.0,2.0,2.0,1.0,...,2.0,2.0,1.0,2.0,3.0,3.0,1.0,1.0,1.0,1.0
438689,1.0,1.0,2.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,...,1.0,6.0,9.0,2.0,1.0,4.0,1.0,1.0,1.0,1.0
438690,3.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,...,1.0,4.0,2.0,4.0,6.0,4.0,1.0,1.0,1.0,1.0
438691,3.0,3.0,2.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,...,1.0,6.0,1.0,2.0,4.0,4.0,1.0,1.0,1.0,1.0
438692,3.0,3.0,2.0,2.0,2.0,1.0,2.0,2.0,2.0,2.0,...,2.0,4.0,2.0,4.0,4.0,4.0,1.0,1.0,2.0,2.0

In [13]:
# Print a list of the new columns
brfss_df_clean.columns.values.tolist()

['DIABETE4',
 'PREDIAB',
 'MEDCOST1',
 '_PHYS14D',
 '_MENT14D',
 'EXERANY2',
 'CVDINFR4',
 'CVDCRHD4',
 'CVDSTRK3',
 'CHCCOPD3',
 'CHCKDNY2',
 'DIFFWALK',
 '_IMPRACE',
 '_RFHLTH',
 '_HLTHPLN',
 '_TOTINDA',
 '_RFHYPE6',
 '_SEX',
 '_AGE_G',
 '_RFBMI5',
 '_EDUCAG',
 '_INCOMG1',
 '_SMOKER3',
 '_RFBING5',
 '_RFDRHV7',
 '_FRTLT1A',
 '_VEGLT1A']



```
# Cleaning our data

2021 BRFSS Codebook CDC: https://www.cdc.gov/brfss/annual_data/2021/pdf/codebook21_llcp-v2-508.pdf 
Codebook for the file showing variable name, location, and frequency of values for all reporting areas combined for the combined landline and cell phone data set.

In [14]:
# DIABETE4
# Make this ordinal: 0 = NO diabetes or only during pregnancy, 1 = YES for diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
brfss_df_clean['DIABETE4'] = brfss_df_clean['DIABETE4'].replace({2:0, 3:0, 4:0})
brfss_df_clean = brfss_df_clean[brfss_df_selected.DIABETE4 != 7]
brfss_df_clean = brfss_df_clean[brfss_df_selected.DIABETE4 != 9]
brfss_df_clean.groupby(['DIABETE4']).size()

DIABETE4
0.0    309494
1.0     48667
dtype: int64

In [15]:
# # PREDIAB
# # Create a duplicate colum for DIABETE4

brfss_df_clean['PREDIAB'] = brfss_df_clean['PREDIAB'].replace({1:0,2:0,3:0,4:1})
brfss_df_clean.groupby(['PREDIAB']).size()

PREDIAB
0.0    349661
1.0      8500
dtype: int64

In [16]:
# MEDCOST1
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don't know and 9 for refused
brfss_df_clean['MEDCOST1'] = brfss_df_clean['MEDCOST1'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean.MEDCOST1 != 7]
brfss_df_clean = brfss_df_clean[brfss_df_clean.MEDCOST1 != 9]
brfss_df_clean.groupby(['MEDCOST1']).size()

MEDCOST1
0.0    331675
1.0     25570
dtype: int64

In [17]:
# _PHYS14D
# 1 = Zero days when physical health not good (Yes) and 0 = one or more days when physical health not good (No value 2 & 3)
# Remove all 9 (refused)
brfss_df_clean['_PHYS14D'] = brfss_df_clean['_PHYS14D'].replace({2:0, 3:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean._PHYS14D != 9]
brfss_df_clean.groupby(['_PHYS14D']).size()

_PHYS14D
0.0    116758
1.0    233313
dtype: int64

In [18]:
# _MENT14D
# 1 = Zero days when mental health not good (YES) and 0 = one or more days when mental health not good (NO value 2 & 3)
# Remove all 9 (refused)
brfss_df_clean['_MENT14D'] = brfss_df_clean['_MENT14D'].replace({2:0, 3:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean._MENT14D != 9]
brfss_df_clean.groupby(['_MENT14D']).size()

_MENT14D
0.0    128223
1.0    217364
dtype: int64

In [19]:
# EXERANY2
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don't know and 9 for refused
brfss_df_clean['EXERANY2'] = brfss_df_clean['EXERANY2'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean.EXERANY2 != 7]
brfss_df_clean = brfss_df_clean[brfss_df_clean.EXERANY2 != 9]
brfss_df_clean.groupby(['EXERANY2']).size()

EXERANY2
0.0     82659
1.0    262449
dtype: int64

In [20]:
# CVDINFR4
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don't know and 9 for refused
brfss_df_clean['CVDINFR4'] = brfss_df_clean['CVDINFR4'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean.CVDINFR4 != 7]
brfss_df_clean = brfss_df_clean[brfss_df_clean.CVDINFR4 != 9]
brfss_df_clean.groupby(['CVDINFR4']).size()

CVDINFR4
0.0    325497
1.0     17976
dtype: int64

In [21]:
# CVDCRHD4
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don't know and 9 for refused
brfss_df_clean['CVDCRHD4'] = brfss_df_clean['CVDCRHD4'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean.CVDCRHD4 != 7]
brfss_df_clean = brfss_df_clean[brfss_df_clean.CVDCRHD4 != 9]
brfss_df_clean.groupby(['CVDCRHD4']).size()

CVDCRHD4
0.0    322636
1.0     18191
dtype: int64

In [22]:
# CVDSTRK3
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don't know and 9 for refused
brfss_df_clean['CVDSTRK3'] = brfss_df_clean['CVDSTRK3'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean.CVDSTRK3 != 7]
brfss_df_clean = brfss_df_clean[brfss_df_clean.CVDSTRK3 != 9]
brfss_df_clean.groupby(['CVDSTRK3']).size()

CVDSTRK3
0.0    327285
1.0     12895
dtype: int64

In [23]:
# CHCCOPD3
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don't know and 9 for refused
brfss_df_clean['CHCCOPD3'] = brfss_df_clean['CHCCOPD3'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean.CHCCOPD3 != 7]
brfss_df_clean = brfss_df_clean[brfss_df_clean.CHCCOPD3 != 9]
brfss_df_clean.groupby(['CHCCOPD3']).size()

CHCCOPD3
0.0    313211
1.0     25890
dtype: int64

In [24]:
# CHCKDNY2
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don't know and 9 for refused
brfss_df_clean['CHCKDNY2'] = brfss_df_clean['CHCKDNY2'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean.CHCKDNY2 != 7]
brfss_df_clean = brfss_df_clean[brfss_df_clean.CHCKDNY2 != 9]
brfss_df_clean.groupby(['CHCKDNY2']).size()

CHCKDNY2
0.0    324954
1.0     13205
dtype: int64

In [25]:
# DIFFWALK
# Change 2 to 0 for no, 1 is already yes
# remove 7 for don't know and 9 for refused
brfss_df_clean['DIFFWALK'] = brfss_df_clean['DIFFWALK'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean.DIFFWALK != 7]
brfss_df_clean = brfss_df_clean[brfss_df_clean.DIFFWALK != 9]
brfss_df_clean.groupby(['DIFFWALK']).size()

DIFFWALK
0.0    285336
1.0     51812
dtype: int64

In [26]:
# _HLTHPLN
# Change 2 to 0 for no, 1 is already yes
# remove 9 for refused
brfss_df_clean['_HLTHPLN'] = brfss_df_clean['_HLTHPLN'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean._HLTHPLN != 9]
brfss_df_clean.groupby(['_HLTHPLN']).size()

_HLTHPLN
0.0     16481
1.0    309889
dtype: int64

In [27]:
# _TOTINDA
# Change 2 to 0 for no, 1 is already yes
# remove 9 for refused
brfss_df_clean['_TOTINDA'] = brfss_df_clean['_TOTINDA'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean._TOTINDA != 9]
brfss_df_clean.groupby(['_TOTINDA']).size()

_TOTINDA
0.0     76711
1.0    249659
dtype: int64

In [28]:
# _RFHYPE6
# Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
# remove 9 for refused
brfss_df_clean['_RFHYPE6'] = brfss_df_clean['_RFHYPE6'].replace({1:0, 2:1})
brfss_df_clean = brfss_df_clean[brfss_df_clean._RFHYPE6 != 9]
brfss_df_clean.groupby(['_RFHYPE6']).size()

_RFHYPE6
0.0    195964
1.0    129608
dtype: int64

In [29]:
# _RFBMI5
# Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
# remove 9 for refused
brfss_df_clean['_RFBMI5'] = brfss_df_clean['_RFBMI5'].replace({1:0, 2:1})
brfss_df_clean = brfss_df_clean[brfss_df_clean._RFBMI5 != 9]
brfss_df_clean.groupby(['_RFBMI5']).size()

_RFBMI5
0.0     93069
1.0    211500
dtype: int64

In [30]:
# _EDUCAG
# remove 9 for refused
brfss_df_clean = brfss_df_clean[brfss_df_clean._EDUCAG != 9]
brfss_df_clean.groupby(['_EDUCAG']).size()

_EDUCAG
1.0     15049
2.0     73740
3.0     84554
4.0    130700
dtype: int64

In [31]:
# _INCOMG1
# remove 9 for refused
brfss_df_clean = brfss_df_clean[brfss_df_clean._INCOMG1 != 9]
brfss_df_clean.groupby(['_INCOMG1']).size()

_INCOMG1
1.0    14974
2.0    24961
3.0    31241
4.0    36017
5.0    82788
6.0    53140
7.0    14926
dtype: int64

In [32]:
# _SMOKER3
# remove 9 for refused
brfss_df_clean = brfss_df_clean[brfss_df_clean._SMOKER3 != 9]
brfss_df_clean.groupby(['_SMOKER3']).size()

_SMOKER3
1.0     24630
2.0      9174
3.0     73059
4.0    150044
dtype: int64

In [33]:
# _RFBING5
# Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
# remove 9 for refused
brfss_df_clean['_RFBING5'] = brfss_df_clean['_RFBING5'].replace({1:0, 2:1})
brfss_df_clean = brfss_df_clean[brfss_df_clean._RFBING5 != 9]
brfss_df_clean.groupby(['_RFBING5']).size()

_RFBING5
0.0    217314
1.0     36513
dtype: int64

In [34]:
# _RFDRHV7
# Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
# remove 9 for refused
brfss_df_clean['_RFDRHV7'] = brfss_df_clean['_RFDRHV7'].replace({1:0, 2:1})
brfss_df_clean = brfss_df_clean[brfss_df_clean._RFDRHV7 != 9]
brfss_df_clean.groupby(['_RFDRHV7']).size()

_RFDRHV7
0.0    236835
1.0     15906
dtype: int64

In [35]:
# _FRTLT1A
# remove 9 for refused
brfss_df_clean['_FRTLT1A'] = brfss_df_clean['_FRTLT1A'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean._FRTLT1A != 9]
brfss_df_clean.groupby(['_FRTLT1A']).size()

_FRTLT1A
0.0     95661
1.0    152223
dtype: int64

In [36]:
# _VEGLT1A
# remove 9 for refused
brfss_df_clean['_VEGLT1A'] = brfss_df_clean['_VEGLT1A'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean._VEGLT1A != 9]
brfss_df_clean.groupby(['_VEGLT1A']).size()

_VEGLT1A
0.0     42836
1.0    200055
dtype: int64

In [37]:
# _SEX
# remove 9 for refused
brfss_df_clean['_SEX'] = brfss_df_clean['_SEX'].replace({1:0, 2:1})
brfss_df_clean.groupby(['_SEX']).size()

_SEX
0.0    116510
1.0    126381
dtype: int64

In [38]:
# _RFHLTH
# remove 9 for refused
brfss_df_clean['_RFHLTH'] = brfss_df_clean['_RFHLTH'].replace({2:0})
brfss_df_clean = brfss_df_clean[brfss_df_clean._VEGLT1A != 9]
brfss_df_clean.groupby(['_RFHLTH']).size()

_RFHLTH
0.0     36494
1.0    206199
9.0       198
dtype: int64

In [39]:
brfss_df_clean

,DIABETE4,PREDIAB,MEDCOST1,_PHYS14D,_MENT14D,EXERANY2,CVDINFR4,CVDCRHD4,CVDSTRK3,CHCCOPD3,...,_SEX,_AGE_G,_RFBMI5,_EDUCAG,_INCOMG1,_SMOKER3,_RFBING5,_RFDRHV7,_FRTLT1A,_VEGLT1A
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,6.0,0.0,2.0,3.0,3.0,0.0,0.0,1.0,1.0
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,6.0,1.0,2.0,2.0,4.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,5.0,1.0,2.0,5.0,4.0,1.0,0.0,1.0,1.0
5,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,6.0,0.0,3.0,4.0,3.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,6.0,1.0,2.0,5.0,3.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438687,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,6.0,0.0,1.0,2.0,4.0,1.0,0.0,1.0,1.0
438688,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,2.0,0.0,2.0,3.0,3.0,0.0,0.0,1.0,1.0
438690,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,4.0,1.0,4.0,6.0,4.0,0.0,0.0,1.0,1.0
438691,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,6.0,0.0,2.0,4.0,4.0,0.0,0.0,1.0,1.0
438692,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,4.0,1.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0

In [40]:
#Rename the columns to make them more readable
brfss_table = brfss_df_clean.rename(columns = {'DIABETE4':'Diabetes',
                                            'PREDIAB':'Pre-Diabetic',    
                                            'MEDCOST1':'Afford Costs',
                                            '_PHYS14D':'Physical Health',
                                            '_MENT14D':'Mental Health',
                                            'EXERANY2':'Exercise 30 Days',
                                            'CVDINFR4':'Heart Attack',
                                            'CVDCRHD4':'Heart Disease',
                                            'CVDSTRK3':'Stroke',
                                            'CHCCOPD3':'Lung Disease',
                                            'CHCKDNY2':'Kidney Disease',
                                            'DIFFWALK':'Difficulty Walking',
                                            '_IMPRACE':'Race/Ethnicity',
                                            '_RFHLTH':'Overall Health',
                                            '_HLTHPLN':"Health Plan",
                                            '_TOTINDA':'Physical Activity',
                                            '_RFHYPE6':'High BP',
                                            '_SEX':'Gender',
                                            '_AGE_G':'Age',
                                            '_RFBMI5':'Overweight/Obese',
                                            '_EDUCAG':'Education',
                                            '_INCOMG1':'Income',
                                            '_SMOKER3':'Smoker',
                                            '_RFBING5':'Binge Drinker',
                                            '_RFDRHV7':'Heavy Drinker',
                                            '_FRTLT1A':'Fruit>1/Day',
                                            '_VEGLT1A':'Veggies>1/Day'})

brfss_table

,Diabetes,Pre-Diabetic,Afford Costs,Physical Health,Mental Health,Exercise 30 Days,Heart Attack,Heart Disease,Stroke,Lung Disease,...,Gender,Age,Overweight/Obese,Education,Income,Smoker,Binge Drinker,Heavy Drinker,Fruit>1/Day,Veggies>1/Day
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,6.0,0.0,2.0,3.0,3.0,0.0,0.0,1.0,1.0
2,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,1.0,6.0,1.0,2.0,2.0,4.0,0.0,0.0,1.0,0.0
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,5.0,1.0,2.0,5.0,4.0,1.0,0.0,1.0,1.0
5,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,...,0.0,6.0,0.0,3.0,4.0,3.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,6.0,1.0,2.0,5.0,3.0,0.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438687,1.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,6.0,0.0,1.0,2.0,4.0,1.0,0.0,1.0,1.0
438688,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,...,1.0,2.0,0.0,2.0,3.0,3.0,0.0,0.0,1.0,1.0
438690,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,4.0,1.0,4.0,6.0,4.0,0.0,0.0,1.0,1.0
438691,0.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.0,6.0,0.0,2.0,4.0,4.0,0.0,0.0,1.0,1.0
438692,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,1.0,4.0,1.0,4.0,4.0,4.0,0.0,0.0,0.0,0.0

In [41]:
brfss_table.dtypes

Diabetes              float64
Pre-Diabetic          float64
Afford Costs          float64
Physical Health       float64
Mental Health         float64
Exercise 30 Days      float64
Heart Attack          float64
Heart Disease         float64
Stroke                float64
Lung Disease          float64
Kidney Disease        float64
Difficulty Walking    float64
Race/Ethnicity        float64
Overall Health        float64
Health Plan           float64
Physical Activity     float64
High BP               float64
Gender                float64
Age                   float64
Overweight/Obese      float64
Education             float64
Income                float64
Smoker                float64
Binge Drinker         float64
Heavy Drinker         float64
Fruit>1/Day           float64
Veggies>1/Day         float64
dtype: object

In [42]:
# Change datatypes
brfss_table = brfss_table.fillna(0)
brfss_final = brfss_table.astype('int')
brfss_final

,Diabetes,Pre-Diabetic,Afford Costs,Physical Health,Mental Health,Exercise 30 Days,Heart Attack,Heart Disease,Stroke,Lung Disease,...,Gender,Age,Overweight/Obese,Education,Income,Smoker,Binge Drinker,Heavy Drinker,Fruit>1/Day,Veggies>1/Day
0,0,0,0,0,0,0,0,0,0,1,...,1,6,0,2,3,3,0,0,1,1
2,1,0,0,1,1,0,0,1,0,0,...,1,6,1,2,2,4,0,0,1,0
3,1,0,0,1,0,1,0,0,0,0,...,1,5,1,2,5,4,1,0,1,1
5,0,0,0,1,1,0,0,0,0,1,...,0,6,0,3,4,3,0,0,0,0
9,0,0,0,0,0,1,0,0,0,0,...,1,6,1,2,5,3,0,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438687,1,0,0,1,1,1,0,0,0,0,...,0,6,0,1,2,4,1,0,1,1
438688,0,0,1,1,0,1,0,0,0,1,...,1,2,0,2,3,3,0,0,1,1
438690,0,0,0,1,1,1,0,0,0,0,...,0,4,1,4,6,4,0,0,1,1
438691,0,0,0,1,1,1,0,0,0,0,...,0,6,0,2,4,4,0,0,1,1
438692,0,0,0,0,0,1,0,0,0,0,...,1,4,1,4,4,4,0,0,0,0

In [44]:
# Save file to CSV 
brfss_final.to_csv('../Resources/diabetes_2021_health_indicators_BRFSS2021.csv', index=False)